defmodule Rexd.Delta.Prototab do
  @moduledoc false
  # Delta command table, generated by scripts/gen_prototab.exs from
  # librsync 2.3.4 src/prototab.c. Do not edit by hand.
  #
  # Rows are {opcode, kind, immediate, len_1, len_2}:
  #
  #   * kind      - :end, :literal, :copy or :reserved
  #   * immediate - for literals, the length encoded by the opcode itself
  #                 (0 when the length follows as an argument)
  #   * len_1     - width in bytes of the first argument
  #                 (literal length, or copy offset)
  #   * len_2     - width in bytes of the second argument (copy length)
  #
  # All arguments are unsigned big-endian integers.

  @table [
    # RS_OP_END
    {0x00, :end, 0, 0, 0},
    # RS_OP_LITERAL_1
    {0x01, :literal, 1, 0, 0},
    # RS_OP_LITERAL_2
    {0x02, :literal, 2, 0, 0},
    # RS_OP_LITERAL_3
    {0x03, :literal, 3, 0, 0},
    # RS_OP_LITERAL_4
    {0x04, :literal, 4, 0, 0},
    # RS_OP_LITERAL_5
    {0x05, :literal, 5, 0, 0},
    # RS_OP_LITERAL_6
    {0x06, :literal, 6, 0, 0},
    # RS_OP_LITERAL_7
    {0x07, :literal, 7, 0, 0},
    # RS_OP_LITERAL_8
    {0x08, :literal, 8, 0, 0},
    # RS_OP_LITERAL_9
    {0x09, :literal, 9, 0, 0},
    # RS_OP_LITERAL_10
    {0x0A, :literal, 10, 0, 0},
    # RS_OP_LITERAL_11
    {0x0B, :literal, 11, 0, 0},
    # RS_OP_LITERAL_12
    {0x0C, :literal, 12, 0, 0},
    # RS_OP_LITERAL_13
    {0x0D, :literal, 13, 0, 0},
    # RS_OP_LITERAL_14
    {0x0E, :literal, 14, 0, 0},
    # RS_OP_LITERAL_15
    {0x0F, :literal, 15, 0, 0},
    # RS_OP_LITERAL_16
    {0x10, :literal, 16, 0, 0},
    # RS_OP_LITERAL_17
    {0x11, :literal, 17, 0, 0},
    # RS_OP_LITERAL_18
    {0x12, :literal, 18, 0, 0},
    # RS_OP_LITERAL_19
    {0x13, :literal, 19, 0, 0},
    # RS_OP_LITERAL_20
    {0x14, :literal, 20, 0, 0},
    # RS_OP_LITERAL_21
    {0x15, :literal, 21, 0, 0},
    # RS_OP_LITERAL_22
    {0x16, :literal, 22, 0, 0},
    # RS_OP_LITERAL_23
    {0x17, :literal, 23, 0, 0},
    # RS_OP_LITERAL_24
    {0x18, :literal, 24, 0, 0},
    # RS_OP_LITERAL_25
    {0x19, :literal, 25, 0, 0},
    # RS_OP_LITERAL_26
    {0x1A, :literal, 26, 0, 0},
    # RS_OP_LITERAL_27
    {0x1B, :literal, 27, 0, 0},
    # RS_OP_LITERAL_28
    {0x1C, :literal, 28, 0, 0},
    # RS_OP_LITERAL_29
    {0x1D, :literal, 29, 0, 0},
    # RS_OP_LITERAL_30
    {0x1E, :literal, 30, 0, 0},
    # RS_OP_LITERAL_31
    {0x1F, :literal, 31, 0, 0},
    # RS_OP_LITERAL_32
    {0x20, :literal, 32, 0, 0},
    # RS_OP_LITERAL_33
    {0x21, :literal, 33, 0, 0},
    # RS_OP_LITERAL_34
    {0x22, :literal, 34, 0, 0},
    # RS_OP_LITERAL_35
    {0x23, :literal, 35, 0, 0},
    # RS_OP_LITERAL_36
    {0x24, :literal, 36, 0, 0},
    # RS_OP_LITERAL_37
    {0x25, :literal, 37, 0, 0},
    # RS_OP_LITERAL_38
    {0x26, :literal, 38, 0, 0},
    # RS_OP_LITERAL_39
    {0x27, :literal, 39, 0, 0},
    # RS_OP_LITERAL_40
    {0x28, :literal, 40, 0, 0},
    # RS_OP_LITERAL_41
    {0x29, :literal, 41, 0, 0},
    # RS_OP_LITERAL_42
    {0x2A, :literal, 42, 0, 0},
    # RS_OP_LITERAL_43
    {0x2B, :literal, 43, 0, 0},
    # RS_OP_LITERAL_44
    {0x2C, :literal, 44, 0, 0},
    # RS_OP_LITERAL_45
    {0x2D, :literal, 45, 0, 0},
    # RS_OP_LITERAL_46
    {0x2E, :literal, 46, 0, 0},
    # RS_OP_LITERAL_47
    {0x2F, :literal, 47, 0, 0},
    # RS_OP_LITERAL_48
    {0x30, :literal, 48, 0, 0},
    # RS_OP_LITERAL_49
    {0x31, :literal, 49, 0, 0},
    # RS_OP_LITERAL_50
    {0x32, :literal, 50, 0, 0},
    # RS_OP_LITERAL_51
    {0x33, :literal, 51, 0, 0},
    # RS_OP_LITERAL_52
    {0x34, :literal, 52, 0, 0},
    # RS_OP_LITERAL_53
    {0x35, :literal, 53, 0, 0},
    # RS_OP_LITERAL_54
    {0x36, :literal, 54, 0, 0},
    # RS_OP_LITERAL_55
    {0x37, :literal, 55, 0, 0},
    # RS_OP_LITERAL_56
    {0x38, :literal, 56, 0, 0},
    # RS_OP_LITERAL_57
    {0x39, :literal, 57, 0, 0},
    # RS_OP_LITERAL_58
    {0x3A, :literal, 58, 0, 0},
    # RS_OP_LITERAL_59
    {0x3B, :literal, 59, 0, 0},
    # RS_OP_LITERAL_60
    {0x3C, :literal, 60, 0, 0},
    # RS_OP_LITERAL_61
    {0x3D, :literal, 61, 0, 0},
    # RS_OP_LITERAL_62
    {0x3E, :literal, 62, 0, 0},
    # RS_OP_LITERAL_63
    {0x3F, :literal, 63, 0, 0},
    # RS_OP_LITERAL_64
    {0x40, :literal, 64, 0, 0},
    # RS_OP_LITERAL_N1
    {0x41, :literal, 0, 1, 0},
    # RS_OP_LITERAL_N2
    {0x42, :literal, 0, 2, 0},
    # RS_OP_LITERAL_N4
    {0x43, :literal, 0, 4, 0},
    # RS_OP_LITERAL_N8
    {0x44, :literal, 0, 8, 0},
    # RS_OP_COPY_N1_N1
    {0x45, :copy, 0, 1, 1},
    # RS_OP_COPY_N1_N2
    {0x46, :copy, 0, 1, 2},
    # RS_OP_COPY_N1_N4
    {0x47, :copy, 0, 1, 4},
    # RS_OP_COPY_N1_N8
    {0x48, :copy, 0, 1, 8},
    # RS_OP_COPY_N2_N1
    {0x49, :copy, 0, 2, 1},
    # RS_OP_COPY_N2_N2
    {0x4A, :copy, 0, 2, 2},
    # RS_OP_COPY_N2_N4
    {0x4B, :copy, 0, 2, 4},
    # RS_OP_COPY_N2_N8
    {0x4C, :copy, 0, 2, 8},
    # RS_OP_COPY_N4_N1
    {0x4D, :copy, 0, 4, 1},
    # RS_OP_COPY_N4_N2
    {0x4E, :copy, 0, 4, 2},
    # RS_OP_COPY_N4_N4
    {0x4F, :copy, 0, 4, 4},
    # RS_OP_COPY_N4_N8
    {0x50, :copy, 0, 4, 8},
    # RS_OP_COPY_N8_N1
    {0x51, :copy, 0, 8, 1},
    # RS_OP_COPY_N8_N2
    {0x52, :copy, 0, 8, 2},
    # RS_OP_COPY_N8_N4
    {0x53, :copy, 0, 8, 4},
    # RS_OP_COPY_N8_N8
    {0x54, :copy, 0, 8, 8},
    # RS_OP_RESERVED_85
    {0x55, :reserved, 85, 0, 0},
    # RS_OP_RESERVED_86
    {0x56, :reserved, 86, 0, 0},
    # RS_OP_RESERVED_87
    {0x57, :reserved, 87, 0, 0},
    # RS_OP_RESERVED_88
    {0x58, :reserved, 88, 0, 0},
    # RS_OP_RESERVED_89
    {0x59, :reserved, 89, 0, 0},
    # RS_OP_RESERVED_90
    {0x5A, :reserved, 90, 0, 0},
    # RS_OP_RESERVED_91
    {0x5B, :reserved, 91, 0, 0},
    # RS_OP_RESERVED_92
    {0x5C, :reserved, 92, 0, 0},
    # RS_OP_RESERVED_93
    {0x5D, :reserved, 93, 0, 0},
    # RS_OP_RESERVED_94
    {0x5E, :reserved, 94, 0, 0},
    # RS_OP_RESERVED_95
    {0x5F, :reserved, 95, 0, 0},
    # RS_OP_RESERVED_96
    {0x60, :reserved, 96, 0, 0},
    # RS_OP_RESERVED_97
    {0x61, :reserved, 97, 0, 0},
    # RS_OP_RESERVED_98
    {0x62, :reserved, 98, 0, 0},
    # RS_OP_RESERVED_99
    {0x63, :reserved, 99, 0, 0},
    # RS_OP_RESERVED_100
    {0x64, :reserved, 100, 0, 0},
    # RS_OP_RESERVED_101
    {0x65, :reserved, 101, 0, 0},
    # RS_OP_RESERVED_102
    {0x66, :reserved, 102, 0, 0},
    # RS_OP_RESERVED_103
    {0x67, :reserved, 103, 0, 0},
    # RS_OP_RESERVED_104
    {0x68, :reserved, 104, 0, 0},
    # RS_OP_RESERVED_105
    {0x69, :reserved, 105, 0, 0},
    # RS_OP_RESERVED_106
    {0x6A, :reserved, 106, 0, 0},
    # RS_OP_RESERVED_107
    {0x6B, :reserved, 107, 0, 0},
    # RS_OP_RESERVED_108
    {0x6C, :reserved, 108, 0, 0},
    # RS_OP_RESERVED_109
    {0x6D, :reserved, 109, 0, 0},
    # RS_OP_RESERVED_110
    {0x6E, :reserved, 110, 0, 0},
    # RS_OP_RESERVED_111
    {0x6F, :reserved, 111, 0, 0},
    # RS_OP_RESERVED_112
    {0x70, :reserved, 112, 0, 0},
    # RS_OP_RESERVED_113
    {0x71, :reserved, 113, 0, 0},
    # RS_OP_RESERVED_114
    {0x72, :reserved, 114, 0, 0},
    # RS_OP_RESERVED_115
    {0x73, :reserved, 115, 0, 0},
    # RS_OP_RESERVED_116
    {0x74, :reserved, 116, 0, 0},
    # RS_OP_RESERVED_117
    {0x75, :reserved, 117, 0, 0},
    # RS_OP_RESERVED_118
    {0x76, :reserved, 118, 0, 0},
    # RS_OP_RESERVED_119
    {0x77, :reserved, 119, 0, 0},
    # RS_OP_RESERVED_120
    {0x78, :reserved, 120, 0, 0},
    # RS_OP_RESERVED_121
    {0x79, :reserved, 121, 0, 0},
    # RS_OP_RESERVED_122
    {0x7A, :reserved, 122, 0, 0},
    # RS_OP_RESERVED_123
    {0x7B, :reserved, 123, 0, 0},
    # RS_OP_RESERVED_124
    {0x7C, :reserved, 124, 0, 0},
    # RS_OP_RESERVED_125
    {0x7D, :reserved, 125, 0, 0},
    # RS_OP_RESERVED_126
    {0x7E, :reserved, 126, 0, 0},
    # RS_OP_RESERVED_127
    {0x7F, :reserved, 127, 0, 0},
    # RS_OP_RESERVED_128
    {0x80, :reserved, 128, 0, 0},
    # RS_OP_RESERVED_129
    {0x81, :reserved, 129, 0, 0},
    # RS_OP_RESERVED_130
    {0x82, :reserved, 130, 0, 0},
    # RS_OP_RESERVED_131
    {0x83, :reserved, 131, 0, 0},
    # RS_OP_RESERVED_132
    {0x84, :reserved, 132, 0, 0},
    # RS_OP_RESERVED_133
    {0x85, :reserved, 133, 0, 0},
    # RS_OP_RESERVED_134
    {0x86, :reserved, 134, 0, 0},
    # RS_OP_RESERVED_135
    {0x87, :reserved, 135, 0, 0},
    # RS_OP_RESERVED_136
    {0x88, :reserved, 136, 0, 0},
    # RS_OP_RESERVED_137
    {0x89, :reserved, 137, 0, 0},
    # RS_OP_RESERVED_138
    {0x8A, :reserved, 138, 0, 0},
    # RS_OP_RESERVED_139
    {0x8B, :reserved, 139, 0, 0},
    # RS_OP_RESERVED_140
    {0x8C, :reserved, 140, 0, 0},
    # RS_OP_RESERVED_141
    {0x8D, :reserved, 141, 0, 0},
    # RS_OP_RESERVED_142
    {0x8E, :reserved, 142, 0, 0},
    # RS_OP_RESERVED_143
    {0x8F, :reserved, 143, 0, 0},
    # RS_OP_RESERVED_144
    {0x90, :reserved, 144, 0, 0},
    # RS_OP_RESERVED_145
    {0x91, :reserved, 145, 0, 0},
    # RS_OP_RESERVED_146
    {0x92, :reserved, 146, 0, 0},
    # RS_OP_RESERVED_147
    {0x93, :reserved, 147, 0, 0},
    # RS_OP_RESERVED_148
    {0x94, :reserved, 148, 0, 0},
    # RS_OP_RESERVED_149
    {0x95, :reserved, 149, 0, 0},
    # RS_OP_RESERVED_150
    {0x96, :reserved, 150, 0, 0},
    # RS_OP_RESERVED_151
    {0x97, :reserved, 151, 0, 0},
    # RS_OP_RESERVED_152
    {0x98, :reserved, 152, 0, 0},
    # RS_OP_RESERVED_153
    {0x99, :reserved, 153, 0, 0},
    # RS_OP_RESERVED_154
    {0x9A, :reserved, 154, 0, 0},
    # RS_OP_RESERVED_155
    {0x9B, :reserved, 155, 0, 0},
    # RS_OP_RESERVED_156
    {0x9C, :reserved, 156, 0, 0},
    # RS_OP_RESERVED_157
    {0x9D, :reserved, 157, 0, 0},
    # RS_OP_RESERVED_158
    {0x9E, :reserved, 158, 0, 0},
    # RS_OP_RESERVED_159
    {0x9F, :reserved, 159, 0, 0},
    # RS_OP_RESERVED_160
    {0xA0, :reserved, 160, 0, 0},
    # RS_OP_RESERVED_161
    {0xA1, :reserved, 161, 0, 0},
    # RS_OP_RESERVED_162
    {0xA2, :reserved, 162, 0, 0},
    # RS_OP_RESERVED_163
    {0xA3, :reserved, 163, 0, 0},
    # RS_OP_RESERVED_164
    {0xA4, :reserved, 164, 0, 0},
    # RS_OP_RESERVED_165
    {0xA5, :reserved, 165, 0, 0},
    # RS_OP_RESERVED_166
    {0xA6, :reserved, 166, 0, 0},
    # RS_OP_RESERVED_167
    {0xA7, :reserved, 167, 0, 0},
    # RS_OP_RESERVED_168
    {0xA8, :reserved, 168, 0, 0},
    # RS_OP_RESERVED_169
    {0xA9, :reserved, 169, 0, 0},
    # RS_OP_RESERVED_170
    {0xAA, :reserved, 170, 0, 0},
    # RS_OP_RESERVED_171
    {0xAB, :reserved, 171, 0, 0},
    # RS_OP_RESERVED_172
    {0xAC, :reserved, 172, 0, 0},
    # RS_OP_RESERVED_173
    {0xAD, :reserved, 173, 0, 0},
    # RS_OP_RESERVED_174
    {0xAE, :reserved, 174, 0, 0},
    # RS_OP_RESERVED_175
    {0xAF, :reserved, 175, 0, 0},
    # RS_OP_RESERVED_176
    {0xB0, :reserved, 176, 0, 0},
    # RS_OP_RESERVED_177
    {0xB1, :reserved, 177, 0, 0},
    # RS_OP_RESERVED_178
    {0xB2, :reserved, 178, 0, 0},
    # RS_OP_RESERVED_179
    {0xB3, :reserved, 179, 0, 0},
    # RS_OP_RESERVED_180
    {0xB4, :reserved, 180, 0, 0},
    # RS_OP_RESERVED_181
    {0xB5, :reserved, 181, 0, 0},
    # RS_OP_RESERVED_182
    {0xB6, :reserved, 182, 0, 0},
    # RS_OP_RESERVED_183
    {0xB7, :reserved, 183, 0, 0},
    # RS_OP_RESERVED_184
    {0xB8, :reserved, 184, 0, 0},
    # RS_OP_RESERVED_185
    {0xB9, :reserved, 185, 0, 0},
    # RS_OP_RESERVED_186
    {0xBA, :reserved, 186, 0, 0},
    # RS_OP_RESERVED_187
    {0xBB, :reserved, 187, 0, 0},
    # RS_OP_RESERVED_188
    {0xBC, :reserved, 188, 0, 0},
    # RS_OP_RESERVED_189
    {0xBD, :reserved, 189, 0, 0},
    # RS_OP_RESERVED_190
    {0xBE, :reserved, 190, 0, 0},
    # RS_OP_RESERVED_191
    {0xBF, :reserved, 191, 0, 0},
    # RS_OP_RESERVED_192
    {0xC0, :reserved, 192, 0, 0},
    # RS_OP_RESERVED_193
    {0xC1, :reserved, 193, 0, 0},
    # RS_OP_RESERVED_194
    {0xC2, :reserved, 194, 0, 0},
    # RS_OP_RESERVED_195
    {0xC3, :reserved, 195, 0, 0},
    # RS_OP_RESERVED_196
    {0xC4, :reserved, 196, 0, 0},
    # RS_OP_RESERVED_197
    {0xC5, :reserved, 197, 0, 0},
    # RS_OP_RESERVED_198
    {0xC6, :reserved, 198, 0, 0},
    # RS_OP_RESERVED_199
    {0xC7, :reserved, 199, 0, 0},
    # RS_OP_RESERVED_200
    {0xC8, :reserved, 200, 0, 0},
    # RS_OP_RESERVED_201
    {0xC9, :reserved, 201, 0, 0},
    # RS_OP_RESERVED_202
    {0xCA, :reserved, 202, 0, 0},
    # RS_OP_RESERVED_203
    {0xCB, :reserved, 203, 0, 0},
    # RS_OP_RESERVED_204
    {0xCC, :reserved, 204, 0, 0},
    # RS_OP_RESERVED_205
    {0xCD, :reserved, 205, 0, 0},
    # RS_OP_RESERVED_206
    {0xCE, :reserved, 206, 0, 0},
    # RS_OP_RESERVED_207
    {0xCF, :reserved, 207, 0, 0},
    # RS_OP_RESERVED_208
    {0xD0, :reserved, 208, 0, 0},
    # RS_OP_RESERVED_209
    {0xD1, :reserved, 209, 0, 0},
    # RS_OP_RESERVED_210
    {0xD2, :reserved, 210, 0, 0},
    # RS_OP_RESERVED_211
    {0xD3, :reserved, 211, 0, 0},
    # RS_OP_RESERVED_212
    {0xD4, :reserved, 212, 0, 0},
    # RS_OP_RESERVED_213
    {0xD5, :reserved, 213, 0, 0},
    # RS_OP_RESERVED_214
    {0xD6, :reserved, 214, 0, 0},
    # RS_OP_RESERVED_215
    {0xD7, :reserved, 215, 0, 0},
    # RS_OP_RESERVED_216
    {0xD8, :reserved, 216, 0, 0},
    # RS_OP_RESERVED_217
    {0xD9, :reserved, 217, 0, 0},
    # RS_OP_RESERVED_218
    {0xDA, :reserved, 218, 0, 0},
    # RS_OP_RESERVED_219
    {0xDB, :reserved, 219, 0, 0},
    # RS_OP_RESERVED_220
    {0xDC, :reserved, 220, 0, 0},
    # RS_OP_RESERVED_221
    {0xDD, :reserved, 221, 0, 0},
    # RS_OP_RESERVED_222
    {0xDE, :reserved, 222, 0, 0},
    # RS_OP_RESERVED_223
    {0xDF, :reserved, 223, 0, 0},
    # RS_OP_RESERVED_224
    {0xE0, :reserved, 224, 0, 0},
    # RS_OP_RESERVED_225
    {0xE1, :reserved, 225, 0, 0},
    # RS_OP_RESERVED_226
    {0xE2, :reserved, 226, 0, 0},
    # RS_OP_RESERVED_227
    {0xE3, :reserved, 227, 0, 0},
    # RS_OP_RESERVED_228
    {0xE4, :reserved, 228, 0, 0},
    # RS_OP_RESERVED_229
    {0xE5, :reserved, 229, 0, 0},
    # RS_OP_RESERVED_230
    {0xE6, :reserved, 230, 0, 0},
    # RS_OP_RESERVED_231
    {0xE7, :reserved, 231, 0, 0},
    # RS_OP_RESERVED_232
    {0xE8, :reserved, 232, 0, 0},
    # RS_OP_RESERVED_233
    {0xE9, :reserved, 233, 0, 0},
    # RS_OP_RESERVED_234
    {0xEA, :reserved, 234, 0, 0},
    # RS_OP_RESERVED_235
    {0xEB, :reserved, 235, 0, 0},
    # RS_OP_RESERVED_236
    {0xEC, :reserved, 236, 0, 0},
    # RS_OP_RESERVED_237
    {0xED, :reserved, 237, 0, 0},
    # RS_OP_RESERVED_238
    {0xEE, :reserved, 238, 0, 0},
    # RS_OP_RESERVED_239
    {0xEF, :reserved, 239, 0, 0},
    # RS_OP_RESERVED_240
    {0xF0, :reserved, 240, 0, 0},
    # RS_OP_RESERVED_241
    {0xF1, :reserved, 241, 0, 0},
    # RS_OP_RESERVED_242
    {0xF2, :reserved, 242, 0, 0},
    # RS_OP_RESERVED_243
    {0xF3, :reserved, 243, 0, 0},
    # RS_OP_RESERVED_244
    {0xF4, :reserved, 244, 0, 0},
    # RS_OP_RESERVED_245
    {0xF5, :reserved, 245, 0, 0},
    # RS_OP_RESERVED_246
    {0xF6, :reserved, 246, 0, 0},
    # RS_OP_RESERVED_247
    {0xF7, :reserved, 247, 0, 0},
    # RS_OP_RESERVED_248
    {0xF8, :reserved, 248, 0, 0},
    # RS_OP_RESERVED_249
    {0xF9, :reserved, 249, 0, 0},
    # RS_OP_RESERVED_250
    {0xFA, :reserved, 250, 0, 0},
    # RS_OP_RESERVED_251
    {0xFB, :reserved, 251, 0, 0},
    # RS_OP_RESERVED_252
    {0xFC, :reserved, 252, 0, 0},
    # RS_OP_RESERVED_253
    {0xFD, :reserved, 253, 0, 0},
    # RS_OP_RESERVED_254
    {0xFE, :reserved, 254, 0, 0},
    # RS_OP_RESERVED_255
    {0xFF, :reserved, 255, 0, 0}
  ]

  @doc false
  def table, do: @table
end
