# Regenerates lib/rexd/delta/prototab.ex from librsync's src/prototab.c.
#
#     mix run scripts/gen_prototab.exs path/to/librsync/src/prototab.c [librsync version]
#
# Each table row in prototab.c has the form
#
#     {RS_KIND_COPY, 0, 1, 2},    /* RS_OP_COPY_N1_N2 = 0x46 */
#
# i.e. kind, immediate length, first argument width, second argument width,
# with the opcode in the trailing comment.

[source | rest] = System.argv()
version = List.first(rest, "2.x")

row =
  ~r/\{RS_KIND_(\w+),\s*(\d+),\s*(\d+),\s*(\d+)\},\s*\/\*\s*(RS_OP_\w+)\s*=\s*(0x[0-9a-fA-F]+|0)\s*\*\//

rows =
  for [_, kind, immediate, len_1, len_2, name, opcode] <- Regex.scan(row, File.read!(source)) do
    {opcode, ""} =
      case opcode do
        "0" -> {0, ""}
        "0x" <> hex -> Integer.parse(hex, 16)
      end

    {opcode, kind |> String.downcase() |> String.to_atom(), String.to_integer(immediate),
     String.to_integer(len_1), String.to_integer(len_2), name}
  end

opcodes = Enum.map(rows, &elem(&1, 0))

unless opcodes == Enum.to_list(0..255) do
  raise "expected 256 rows for opcodes 0x00..0xFF in order, got #{length(rows)}"
end

lines =
  Enum.map_join(rows, ",\n", fn {op, kind, imm, l1, l2, name} ->
    hex = op |> Integer.to_string(16) |> String.pad_leading(2, "0")
    "    # #{name}\n    {0x#{hex}, #{inspect(kind)}, #{imm}, #{l1}, #{l2}}"
  end)

module = """
defmodule Rexd.Delta.Prototab do
  @moduledoc false
  # Delta command table, generated by scripts/gen_prototab.exs from
  # librsync #{version} src/prototab.c. Do not edit by hand.
  #
  # Rows are {opcode, kind, immediate, len_1, len_2}:
  #
  #   * kind      - :end, :literal, :copy or :reserved
  #   * immediate - for literals, the length encoded by the opcode itself
  #                 (0 when the length follows as an argument)
  #   * len_1     - width in bytes of the first argument
  #                 (literal length, or copy offset)
  #   * len_2     - width in bytes of the second argument (copy length)
  #
  # All arguments are unsigned big-endian integers.

  @table [
#{lines}
  ]

  @doc false
  def table, do: @table
end
"""

File.write!("lib/rexd/delta/prototab.ex", module)
IO.puts("wrote lib/rexd/delta/prototab.ex (#{length(rows)} opcodes)")
