# Regenerates test/fixtures/vectors.term from the reference tools.
#
#     mix run scripts/gen_vectors.exs
#
# Requires `rdiff` (librsync 2.x) and `b2sum` on PATH. The inputs are
# deterministic, so re-running with the same tool versions yields the same
# file. The fixture lets the wire-compatibility tests run where the tools are
# not installed.

defmodule GenVectors do
  import Bitwise

  # Deterministic byte stream (64-bit LCG, top byte of each state).
  def bytes(n, seed) do
    {acc, _} =
      Enum.reduce(1..n//1, {[], seed}, fn _, {acc, s} ->
        s = s * 6_364_136_223_846_793_005 + 1_442_695_040_888_963_407 &&& 0xFFFFFFFFFFFFFFFF
        {[s >>> 56 | acc], s}
      end)

    acc |> Enum.reverse() |> :erlang.list_to_binary()
  end

  def cmd!(tool, args) do
    {out, 0} = System.cmd(tool, args, stderr_to_stdout: true)
    out
  end

  def hex(bin), do: Base.encode16(bin, case: :lower)
end

dir = Path.join(System.tmp_dir!(), "rexd-vectors-#{System.unique_integer([:positive])}")
File.mkdir_p!(dir)

text = GenVectors.bytes(2000, 42)
<<t1::binary-size(700), t2::binary-size(300), t3::binary>> = text
sixty_four = GenVectors.bytes(64, 7)
<<b0::binary-16, b1::binary-16, b2::binary-16, b3::binary-16>> = sixty_four

cases = [
  {"empty basis", "", "abc", 16, 32},
  {"empty new", "hello world", "", 4, 32},
  {"both empty", "", "", 8, 32},
  {"short text", "hello world, this is rexd", "hello brave world, this is rexd!", 8, 8},
  {"block_len larger than input", "tiny basis", "tiny basis, grown", 2048, 32},
  {"exact multiple, blocks moved", sixty_four, b2 <> b0 <> b3 <> b1, 16, 32},
  {"all zero", :binary.copy(<<0>>, 200), :binary.copy(<<0>>, 150) <> "x", 32, 32},
  {"insert delete replace", text, t1 <> "INSERTED" <> t3 <> binary_part(t2, 0, 100), 256, 16},
  {"strong_sum_len 1", text, t3 <> t1, 128, 1},
  {"literal over 64 bytes", "abc", GenVectors.bytes(300, 9), 16, 32}
]

signature_vectors =
  for {name, basis, new, block_len, strong_sum_len} <- cases do
    basis_path = Path.join(dir, "basis")
    new_path = Path.join(dir, "new")
    sig_path = Path.join(dir, "sig")
    delta_path = Path.join(dir, "delta")
    File.write!(basis_path, basis)
    File.write!(new_path, new)

    GenVectors.cmd!("rdiff", [
      "-f",
      "-b",
      "#{block_len}",
      "-S",
      "#{strong_sum_len}",
      "signature",
      basis_path,
      sig_path
    ])

    GenVectors.cmd!("rdiff", ["-f", "delta", sig_path, new_path, delta_path])

    %{
      name: name,
      block_len: block_len,
      strong_sum_len: strong_sum_len,
      basis: GenVectors.hex(basis),
      new: GenVectors.hex(new),
      rdiff_signature: GenVectors.hex(File.read!(sig_path)),
      rdiff_delta: GenVectors.hex(File.read!(delta_path))
    }
  end

blake2b_vectors =
  for len <- [0, 1, 3, 63, 64, 65, 127, 128, 129, 255, 256, 257, 1024, 2048, 4097] do
    data = GenVectors.bytes(len, 1000 + len)
    path = Path.join(dir, "b2")
    File.write!(path, data)
    [digest | _] = String.split(GenVectors.cmd!("b2sum", ["-l", "256", path]))
    %{data: GenVectors.hex(data), blake2b_256: digest}
  end

[rdiff_version | _] = String.split(GenVectors.cmd!("rdiff", ["--version"]), "\n")

header = """
# Generated by scripts/gen_vectors.exs with #{rdiff_version} and b2sum.
# Do not edit by hand.
"""

body =
  inspect(%{signatures: signature_vectors, blake2b: blake2b_vectors},
    pretty: true,
    limit: :infinity,
    printable_limit: :infinity
  )

File.write!("test/fixtures/vectors.term", header <> body <> "\n")
File.rm_rf!(dir)

IO.puts(
  "wrote test/fixtures/vectors.term (#{length(cases)} rdiff cases, #{length(blake2b_vectors)} BLAKE2b digests)"
)
